<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Dragon Fruit',
                'sku' => 'DF024',
                'price' => 150.00,
                'old_price' => 200.00,
                'discount' => 25,
                'image' => 'images/dragonfruit.png',
                'stock' => 22,
                'stock_online' => 2,
                'stock_marketplace' => 2,
                'stock_retail' => 5,
                'stock_warehouse_a' => 13,
                'reviews_count' => 150,
                'flash_sale' => true,
                'featured' => true,
                'sold' => 45,
                'description' => 'Sweet, juicy, and packed with nutrients. Dragon Fruit is rich in antioxidants, Vitamin C, fiber, and minerals. Freshly harvested from local farms.',
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Mango',
                'sku' => 'FR001',
                'price' => 120.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/mango.png',
                'stock' => 140,
                'stock_online' => 65,
                'stock_marketplace' => 20,
                'stock_retail' => 15,
                'stock_warehouse_a' => 40,
                'reviews_count' => 88,
                'flash_sale' => false,
                'featured' => true,
                'sold' => 95,
                'description' => 'Fresh and sweet Philippine Mangoes.',
            ],
            [
                'id' => 3,
                'category_id' => 4,
                'name' => 'Honey',
                'sku' => 'HN015',
                'price' => 250.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/honey.png',
                'stock' => 220,
                'stock_online' => 110,
                'stock_marketplace' => 60,
                'stock_retail' => 20,
                'stock_warehouse_a' => 30,
                'reviews_count' => 120,
                'flash_sale' => false,
                'featured' => true,
                'sold' => 180,
                'description' => 'Pure organic wild honey.',
            ],
            [
                'id' => 4,
                'category_id' => 2,
                'name' => 'Cabbage',
                'sku' => 'CB016',
                'price' => 60.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/cabbage.png',
                'stock' => 10,
                'stock_online' => 0,
                'stock_marketplace' => 0,
                'stock_retail' => 2,
                'stock_warehouse_a' => 8,
                'reviews_count' => 45,
                'flash_sale' => false,
                'featured' => false,
                'sold' => 22,
                'description' => 'Fresh green cabbage from local farms.',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Banana',
                'sku' => 'BN020',
                'price' => 75.00,
                'old_price' => 95.00,
                'discount' => 21,
                'image' => 'images/banana.png',
                'stock' => 155,
                'stock_online' => 85,
                'stock_marketplace' => 31,
                'stock_retail' => 14,
                'stock_warehouse_a' => 25,
                'reviews_count' => 90,
                'flash_sale' => true,
                'featured' => true,
                'sold' => 120,
                'description' => 'Fresh sweet organic bananas.',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Orange',
                'sku' => 'OR002',
                'price' => 130.00,
                'old_price' => 150.00,
                'discount' => 13,
                'image' => 'images/orange.png',
                'stock' => 150,
                'stock_online' => 50,
                'reviews_count' => 65,
                'flash_sale' => true,
                'featured' => true,
                'sold' => 110,
                'description' => 'Sweet and juicy oranges.',
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'name' => 'Grapes',
                'sku' => 'GR005',
                'price' => 220.00,
                'old_price' => 250.00,
                'discount' => 12,
                'image' => 'images/grapes.png',
                'stock' => 80,
                'reviews_count' => 78,
                'flash_sale' => true,
                'featured' => true,
                'sold' => 130,
                'description' => 'Seedless sweet red grapes.',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Tomato',
                'sku' => 'TM004',
                'price' => 60.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/tomato.png',
                'stock' => 100,
                'reviews_count' => 34,
                'flash_sale' => false,
                'featured' => false,
                'sold' => 50,
                'description' => 'Fresh red organic tomatoes.',
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'name' => 'Cucumber',
                'sku' => 'CC008',
                'price' => 80.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/cucumber.png',
                'stock' => 120,
                'reviews_count' => 56,
                'flash_sale' => false,
                'featured' => false,
                'sold' => 40,
                'description' => 'Crispy organic cucumber.',
            ],
            [
                'id' => 10,
                'category_id' => 2,
                'name' => 'Carrot',
                'sku' => 'CR009',
                'price' => 95.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/carrot.png',
                'stock' => 90,
                'reviews_count' => 48,
                'flash_sale' => false,
                'featured' => false,
                'sold' => 35,
                'description' => 'Fresh sweet carrots.',
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'Lettuce',
                'sku' => 'LT010',
                'price' => 70.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/lettuce.png',
                'stock' => 110,
                'reviews_count' => 72,
                'flash_sale' => false,
                'featured' => false,
                'sold' => 80,
                'description' => 'Green crunchy lettuce leaves.',
            ],
            [
                'id' => 12,
                'category_id' => 1,
                'name' => 'Pineapple',
                'sku' => 'PA012',
                'price' => 120.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/pineapple.png',
                'stock' => 85,
                'reviews_count' => 50,
                'flash_sale' => false,
                'featured' => true,
                'sold' => 65,
                'description' => 'Sweet pineapple harvested fresh.',
            ],
            [
                'id' => 13,
                'category_id' => 6,
                'name' => 'Cacao Beans',
                'sku' => 'CB030',
                'price' => 210.00,
                'old_price' => null,
                'discount' => null,
                'image' => 'images/cacao.png',
                'stock' => 60,
                'reviews_count' => 30,
                'flash_sale' => false,
                'featured' => true,
                'sold' => 25,
                'description' => 'Premium local cacao beans.',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }
}
